### ISSUE TITLE
How to build BUILD.gn

### ISSUE THREAD

**Issue by abakre** [bayandin/chromedriver#2]
Hi,
New to Chromedriver and Chromium. I have downloaded your GIT repo and wanted to build Chromedriver. 
Could you please help me with instructions on how to build BUILD.gn?

Tried:
gn gen out/a in the source folder which has BUILD.gn
ERROR Can't find source root.
I could not find a ".gn" file in the current directory or any parent,
and the --root command-line argument was not specified.

Thanks,
AB

**Comment by bayandin** [comment]
Hey @abakre, for building the driver you need to clone entire [chromium](https://chromium.googlesource.com/chromium/src) repo and after that follow this instruction https://sites.google.com/a/chromium.org/chromedriver/contributing
